### ISSUE TITLE
Модель игры в шашки

### ISSUE THREAD

**Issue by aaa2407** [aaa2407/Checkers#1]
Сделать диаграмму классов для модели  игры "Шашки".
Модель должна включать в себя:
A) шахматную доску;
Б) шашки
             Она имеет 2 вида состояния: 
                    - Простая/Дамка
                    - Белая/Черная
В) ходьба 
             В объекте этого класса есть 2 вида состояния:  
                        - ход с поеданием/без
                        - игра простой фигурой/дамкой
             Если без поедания, то он состоит из начального и конечного положений шашки
             Если ход с поеданием, то он также может включать промежуточное положение шашки   
               (если, например, он есть дважды за ход) и обязан включать список съеденных шашек 
               (или список положений этих съеденных шашек)
             Также должен быть флажок перехода состояния из простой шашки в дамку.
            
Г) Игрок
             В объекте этого класса имеет 2 вида состояний:
                      - черный/белый (константа)
                      - активен/неактивен
             Игрок может осуществлять ход, только если он активен.
             От  этого объекта должны передаваться объекты ходы на шахматную доску
             В дальнейшем у этого класса будут три дочерних: Пользователь, Бот, Сервер

Д) Таймер 
             Он должен запускаться, когда игроку предоставляется ход.
             Если таймер истек и игрок не передал объект ходьбы, то управление передается другому
                 игроку.
             Объект может входить  в 2 дочерних от Игрока класса: Пользователь и Сервер

Правила игры в шашки: http://www.gambler.ru/%CF%F0%E0%E2%E8%EB%E0_%F0%F3%F1%F1%EA%E8%F5_%F8%E0%F8%E5%EA

**Comment by denis96z** [comment]
1) Класс "Ходьба" заменен на более обобщенный класс "Игра".
2) Из интерфейса при поедании подается команда для удара только по одной шашке. Далее, в случае когда необходимо съесть две и более шашки,  передача хода другому игроку не происходит и пользователь производит удар по следующей шашке.

**Comment by aaa2407** [comment]
Дополнение про шахматную доску.
В данном классе должен быть метод, параметром которого является объект ходьбы,  и возвращать обновленную доску.
